/**
 * Channel manifest loader — reads the pre-generated JSON at build time.
 * The manifest is generated by: npm run fetch-channels
 * and committed to scripts/channel-manifest.json.
 * On Render, the build command regenerates it before next build.
 */

export interface ChannelManifest {
  generatedAt: string
  totalChannels: number
  /** countryName → array of channel display names */
  countries: Record<string, string[]>
}

export interface ChannelEntry {
  name: string
  slug: string
  countryName: string
  countrySlug: string
}

// Convert a display name to a URL slug
export function toChannelSlugManifest(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

export function toCountrySlugManifest(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

// Lazy-loaded at build time only — never imported in client bundles
let _manifest: ChannelManifest | null = null

export function getChannelManifest(): ChannelManifest {
  if (_manifest) return _manifest
  // Dynamic require keeps this out of the client bundle
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  _manifest = require('../../scripts/channel-manifest.json') as ChannelManifest
  return _manifest
}

/** Returns all [countrySlug, channelSlug] pairs for generateStaticParams */
export function getAllChannelParams(): { country: string; channel: string }[] {
  const manifest = getChannelManifest()
  const params: { country: string; channel: string }[] = []
  const seen = new Set<string>()

  for (const [countryName, channels] of Object.entries(manifest.countries)) {
    const countrySlug = toCountrySlugManifest(countryName)
    for (const channelName of channels) {
      const channelSlug = toChannelSlugManifest(channelName)
      if (!channelSlug) continue
      const key = `${countrySlug}::${channelSlug}`
      if (seen.has(key)) continue
      seen.add(key)
      params.push({ country: countrySlug, channel: channelSlug })
    }
  }

  return params
}

/** Look up a channel's display name from its slug within a country */
export function getChannelFromManifest(
  countrySlug: string,
  channelSlug: string
): { name: string; countryName: string } | null {
  const manifest = getChannelManifest()

  for (const [countryName, channels] of Object.entries(manifest.countries)) {
    if (toCountrySlugManifest(countryName) !== countrySlug) continue
    for (const channelName of channels) {
      if (toChannelSlugManifest(channelName) === channelSlug) {
        return { name: channelName, countryName }
      }
    }
  }
  return null
}

/** Get all channels for a given country slug */
export function getCountryChannelsFromManifest(
  countrySlug: string
): { name: string; slug: string }[] {
  const manifest = getChannelManifest()

  for (const [countryName, channels] of Object.entries(manifest.countries)) {
    if (toCountrySlugManifest(countryName) !== countrySlug) continue
    return channels.map(name => ({
      name,
      slug: toChannelSlugManifest(name),
    }))
  }
  return []
}

/** Total unique channel count from the manifest */
export function getTotalChannelCount(): number {
  return getChannelManifest().totalChannels
}
